name: "arrow-incubator: build"

on: pull_request

jobs:
  arrow-incubator_build:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m
      ARROW_LIB: arrow-incubator

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Checkout orchestrator
      run: |
        cd $BASEDIR
        git clone https://github.com/arrow-kt/arrow.git
    - name: Build with Gradle
      run: |
        $BASEDIR/arrow/scripts/project-build.sh $ARROW_LIB
    - name: Run benchmarks
      run: |
        ./gradlew :arrow-benchmarks-free:jmhForArrow
        ./gradlew :arrow-benchmarks-free:jmhForCats
    - name: Run benchmark comparison
      env:
        CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export PULL_REQUEST_NUMBER=$(echo $GITHUB_REF | cut -d/ -f3)
        ./gradlew :arrow-benchmarks-free:compareBenchmarksCI
